# colorschemes --------------------------------------------
[[plugins]]
repo = 'sff1019/vim-brogrammer-theme'
# hook_add = '''
#     set background=dark
# '''

[[plugins]]
repo = 'nielsmadan/harlequin'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme harlequin
# '''

[[plugins]]
repo = 'ajh17/Spacegray.vim'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme spacegray
# '''

[[plugins]]
repo = 'whatyouhide/vim-gotham'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme gotham
# '''am'

[[plugins]]
repo = 'fenetikm/falcon'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme falcon
# '''

[[plugins]]
repo = 'sff1019/vim-joker'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme joker
# '''r'

[[plugins]]
repo = 'sjl/badwolf'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme badwolf
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
# hook_add = '''
#     set background=dark
# '''

[[plugins]]
repo = 'mhartington/oceanic-next'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'tlhr/anderson.vim'

[[plugins]]
repo = 'srcery-colors/srcery-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
