# colorschemes --------------------------------------------
[[plugins]]
repo = 'sff1019/vim-brogrammer-theme'

[[plugins]]
repo = 'sff1019/vim-joker'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tlhr/anderson.vim'

[[plugins]]
repo = 'raphamorim/lucario'
