[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
hook_add = """
  let g:coc_global_config="$HOME/.config/nvim/plugins/coc-settings.json"
  source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'roxma/nvim-yarp'
on-if = '''! has('nvim')'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

# airline -----------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_theme = 'tomorrow'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'default'
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#fnamemod = ':t'
  let g:airline#extensions#tabline#left_alt_sep = ' '
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# fzf ----------------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
hook_add = '''
  command! -bang -nargs=* Rg
        \ call fzf#vim#grep(
        \   'rg -g "!node_modules/*" --column --line-number  --no-heading --color=always '.shellescape(<q-args>), 0,
        \   fzf#vim#with_preview({'options': '--exact --delimiter : --nth 3..'}, 'right:50%'))
  nnoremap <silent> <C-t> :FZF<CR>
  nnoremap ,g :Rg<CR>
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# # git ----------------------------------------------------
# [[plugins]]
# repo = 'airblade/vim-gitgutter'
#
# [[plugins]]
# repo = 'tpope/vim-fugitive'
#
# # colorization -------------------------------------------
# [[plugins]]
# repo = 'vim-scripts/AnsiEsc.vim'
#

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# easy motion --------------------------------------------
[[plugins]]
repo = 'easymotion/vim-easymotion'

